name: Build containers

on:
  pull_request:
    paths:
      - '*/Dockerfile'

jobs:
  setup:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    outputs:
      matrix: ${{ steps.export-directories.outputs.matrix }}
      all_changed_files_count: ${{ steps.changed-directories.outputs.all_changed_files_count }}

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Get branch name
        id: branch-name
        uses: tj-actions/branch-names@v7

      - name: Get SHA of last commit to main branch
        uses: nrwl/nx-set-shas@v4
        id: last_successful_commit_pull_request
        with:
          main-branch-name: ${{ steps.branch-name.outputs.base_ref_branch }}

      - name: Get changed directories
        id: changed-directories
        uses: tj-actions/changed-files@v46
        with: 
          base_sha: ${{ steps.last_successful_commit_pull_request.outputs.base }}
          dir_names: true
          dir_names_exclude_current_dir: true
          json: true
          files: |
            */Dockerfile

      - name: Export changed directories
        if: steps.changed-directories.outputs.all_changed_files_count > 0
        id: export-directories
        run: |
          echo "matrix={\"context\":${{ steps.changed-directories.outputs.all_changed_files }}}" > /tmp/changed_directories.json
          echo "matrix={\"context\":${{ steps.changed-directories.outputs.all_changed_files }}}" >> "$GITHUB_OUTPUT"

      - name: Upload changed directories
        if: steps.changed-directories.outputs.all_changed_files_count > 0
        uses: actions/upload-artifact@v4
        with:
          name: changed_directories_${{ github.event.pull_request.head.sha }}
          path: /tmp/changed_directories.json

  docker_container:
    needs: setup
    if: needs.setup.outputs.all_changed_files_count > 0
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix: ${{ fromJSON(needs.setup.outputs.matrix) }}

    steps:
      - name: Checkout pull request branch
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main

      - name: Setup up docker buildx
        uses: docker/setup-buildx-action@v3

      - name: Build docker containers
        uses: docker/build-push-action@v6
        with:
          context: ${{ matrix.context }}
          tags: ${{ matrix.context }}:latest
          outputs: type=image,compression=zstd
